### ISSUE TITLE
No blend files export

### ISSUE THREAD

**Issue by Shaun-Fong** [freemocap/freemocap#367]
![image](https://user-images.githubusercontent.com/16713354/231115678-b6da6183-2c4f-4b46-bfc7-d43072eb33e3.png)

ui freeze and blend file not export

**Comment by philipqueen** [comment]
Hello @Shaun-Fong, sorry for such a delay in responding to you. It would be helpful to know which blender export method you are using from this list:
<img width="515" alt="Screen Shot 2023-04-26 at 10 27 01 AM" src="https://user-images.githubusercontent.com/24758117/234641043-1d031445-14d0-4c24-be6a-04917de5f9cd.png">

**Comment by Shaun-Fong** [comment]
> Hello @Shaun-Fong, sorry for such a delay in responding to you. It would be helpful to know which blender export method you are using from this list: <img alt="Screen Shot 2023-04-26 at 10 27 01 AM" width="515" src="https://user-images.githubusercontent.com/24758117/234641043-1d031445-14d0-4c24-be6a-04917de5f9cd.png">

that's okay. I'm using default method.

**Comment by philipqueen** [comment]
Great, can you also try updating your freemocap download `pip install freemocap~=1.0.12rc0` - We were having a problem with the blender output not being able to handle Nan values which should have been solved by now, I think trying the latest version would be a good first step

**Comment by Shaun-Fong** [comment]
> 

Okay I will try ASAP. I will keep you updated.

**Comment by Shaun-Fong** [comment]
> Great, can you also try updating your freemocap download `pip install freemocap~=1.0.12rc0` - We were having a problem with the blender output not being able to handle Nan values which should have been solved by now, I think trying the latest version would be a good first step

hi @philipqueen , may I know what version of blender you are using?

**Comment by Shaun-Fong** [comment]
@philipqueen I'm using 2.8.3 and it still doesn't work under the Default method. But it works under the Legacy method.

**Comment by philipqueen** [comment]
Is there a reason you're using an older version of Blender? I'm not an animator so I'm not very clear on the differences between versions. If there's some good reason to use an older rather than newer version of Blender it will be more worth it to try to get the Default method working with the older version.
It may also just not be possible to have one method work with both versions of Blender, I'm not very familiar with the Blender output side of things.
